sonar.projectKey=victortorreblanca_AS241S5_AEJ_40-be
sonar.organization=victortorreblanca
sonar.host.url=https://sonarcloud.io

# Lenguaje
sonar.language=java
sonar.java.source=17

# Rutas del código
sonar.sources=src/main/java
sonar.tests=src/test/java

# Exclusiones
sonar.exclusions=**/target/**,**/model/**,**/dto/**,**/config/**

# Binarios
sonar.java.binaries=target/classes
