apiVersion: v1
kind: Service
metadata:
  name: victor-torreblanca-40-service
  namespace: victor-torreblanca-40-namespace
spec:
  type: NodePort
  ports:
  - port: 30040
    targetPort: 8080
    nodePort: 30040
  selector:
    app: victor-torreblanca-40-deployment
